modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT Licence"

[[mods]]
modId = "boatfix"
version = "1.0.0"
displayName = "BoatFix"
description = '''
Lets you eat while moving in a boat using the W key.
'''
authors = "Maxi"
logoFile="logo.png"
[[dependencies.boatfix]]
modId = "forge"
mandatory = true
versionRange = "[47.0.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.boatfix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "CLIENT"
